### ISSUE TITLE
Travis builds are down

### ISSUE THREAD

**Issue by sckott** [ropensci/travis-restarts#8]
not sure what the problem is. 

``` ruby
rake runtravis --trace
```

``` ruby
** Invoke runtravis (first_time)
** Execute runtravis
rake aborted!
NoMethodError: undefined method `curry=' for nil:NilClass
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/travis-1.7.2/lib/travis/client/namespace.rb:15:in `find_one'
/Users/sacmac/github/ropensci/travis-restarts/Rakefile:4:in `restart_travis'
/Users/sacmac/github/ropensci/travis-restarts/Rakefile:38:in `block (2 levels) in <top (required)>'
/Users/sacmac/github/ropensci/travis-restarts/Rakefile:37:in `each'
/Users/sacmac/github/ropensci/travis-restarts/Rakefile:37:in `block in <top (required)>'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/task.rb:240:in `call'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/task.rb:240:in `block in execute'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/task.rb:235:in `each'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/task.rb:235:in `execute'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/task.rb:165:in `invoke'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:150:in `invoke_task'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:106:in `each'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:106:in `block in top_level'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:115:in `run_with_threads'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:100:in `top_level'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:78:in `block in run'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:75:in `run'
/Users/sacmac/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.3.1/bin/rake:33:in `<top (required)>'
/Users/sacmac/.rbenv/versions/2.1.0/bin/rake:23:in `load'
/Users/sacmac/.rbenv/versions/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => runtravis
```

**Comment by dquimper** [comment]
Hi! I have the same issue. 
Would happen to remember how you fixed this issue?

**Comment by sckott** [comment]
are you using the code in this repo, or do you just mean this error with different code?

**Comment by dquimper** [comment]
This error with different code.

**Comment by sckott** [comment]
dont remember, i think i've seen that error with many different gems. i guess in this case it was with the travis gem, guessing it was resolved by installing a new version of the gem or ruby maybe
